server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 엔드포인트 노출